### ISSUE TITLE
BOM needs more info/alternate sources for parts

### ISSUE THREAD

**Issue by cmcraft** [PaulKlinger/ndice#1]
>Manufacturer Part   Number | Description | Quantity
>  -- | -- | --
>  ATTINY1614-SSFR | MCU | 1
>  K2-1112SA-A4SW-01 | smd side switch | 2
>  -- | 0805 10K smd resistor | 6
>  -- | 0805 10uf smd ceramic cap | 1
>  -- | 0805 yellow smd LED | 6
>   RV09 B100K B104 | 100K potentiometer 12.5mm through hole | 1

Can we have a more verbose BOM with alternate part numbers or links? I'm trying to build out this project in octopart and I'm having issues sourcing a number of components. 

for instance:  K2-1112SA-A4SW-01 is referring to a specific tactile switch that I may be able to source via alibaba but I'm not sure on 0805 10uf smd ceramic cap. What is the voltage on that cap? Does it matter? I apologize if I'm asking dumb questions as this is my first open source hardware project.

**Comment by PaulKlinger** [comment]
I don't really have too much information for these parts, I just ordered them off aliexpress, over several years.  You're lucky to get a crappy image with dimensions on there, let alone a part number or datasheet.

The side switch is available [here](https://www.aliexpress.com/item/50pcs-3-6mm-SMD-light-touch-switch-2-pin-side-button-Micro-switch-button-switches-3mm/32311331185.html).

I bought the potentiometers from [here](https://www.aliexpress.com/item/10pcs-x-RV09-vertical-12-5mm-Shaft-5K-10K-50K-100K-0932-Adjustable-Resistor-9-type/32897258726.html). (I don't think I wrote this anywhere but you need to cut off the top of the potentiometer knob to fit the 3d printed cap on it. It's pretty soft plastic, so that's no problem.)

The voltage rating for the capacitor doesn't matter; I don't think there are any that can't handle the 3V from the coin cell. (Anyway, the ATtiny's are pretty tolerant, it would probably work just fine even without the cap.)

[And here's](https://www.aliexpress.com/item/5mX-Transparent-side-glow-plastic-PMMA-fiber-optic-cable-solid-core-optic-cable-diameter-2mm-3mm/32807597828.html) where I bought  the optic fiber that guides the light up from the leds. 

Please send me a picture if you build one of these dice, I'd love to see it 😃

**Comment by cmcraft** [comment]
Hey Paul!

Thanks for the build notes! This should help out at least a little.

**Comment by PaulKlinger** [comment]
I've just added a lot more build tips to the [readme](https://github.com/PaulKlinger/ndice/blob/master/README.md) and added the battery holder to the bom.

Sorry that it was so sparse in the beginning, I didn't really think anyone would want to build one ;)

**Comment by cmcraft** [comment]
Qty | Line Item | Manufacturer | MPN | Octopart URL | Schematic Reference | Internal Part Number | Description | Total Qty (@ Batch Size: 1) | SKU | SKU | Packaging | Packaging | Unit Price (@ Batch Size: 1) | Unit Price (@ Batch Size: 1) | In Stock | In Stock | MOQ | MOQ | URL | URL | Distributor [Lowest Price (Overall)] | SKU [Lowest Price (Overall)] | Packaging [Lowest Price (Overall)] | Unit Price (@ Batch Size: 1) [Lowest Price   (Overall)] | Line Total [Lowest Price (Overall)] | Batch Total [Lowest Price (Overall)] | In Stock [Lowest Price (Overall)] | MOQ [Lowest Price (Overall)] | URL [Lowest Price (Overall)] | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser |   |   |   |   |   |   |   |   |   |  
1 | ATTINY1614-SSFR | Microchip | ATTINY1614-SSFR | https://octopart.com/attiny1614-ssfr-microchip-82181131 | 1 | ATTINY1614-SSFRCT-ND | ATTINY1614-SSFR | Cut Tape | 0.75 | 0.75 | 4187 | 4507 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0a83d4a&sid=459&ppid=82181131&vpid=431492422&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=014fdb8&sid=2401&ppid=82181131&vpid=447257214&ct=offers | Arrow Electronics, Inc. | ATTINY1614-SSFR | Cut Tape | 0.7314 | 0.7314 | 0.7314 | 2771 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=05768f2&sid=1106&ppid=82181131&vpid=473294420&ct=offers
6 | ERA-6ARW103V | Panasonic | ERA-6ARW103V | https://octopart.com/era-6arw103v-panasonic-20327930 | 6 | P10KBSCT-ND | ERA-6ARW103V | Cut Tape | 0.79 | 0.79 | 41899 | 8617 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=08efee0&sid=459&ppid=20327930&vpid=88305980&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=04ccc50&sid=2401&ppid=20327930&vpid=43477964&ct=offers | Newark | 50W0872 | 0.286 | 1.716 | 1.716 | 0 |   | https://octopart.com/click/track?c=1&ak=39ac400e&sig=09ee076&sid=2402&ppid=20327930&vpid=81552968&ct=offers
1 | GRM21BR61C106KE15L | Murata | GRM21BR61C106KE15L | https://octopart.com/grm21br61c106ke15l-murata-197438 | 1 | 490-3886-1-ND | GRM21BR61C106KE15L | Cut Tape | 0.32 | 0.36 | 5E+06 | 1E+06 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0d5de69&sid=459&ppid=197438&vpid=1827596&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0187e19&sid=2401&ppid=197438&vpid=38925211&ct=offers | Conrad | 450891 |   | 0.1585 | 0.1585 | 0.1585 | 3263 |   | https://octopart.com/click/track?ak=39ac400e&sig=0ed9acd&sid=14587&ppid=197438&vpid=410932726&ct=offers
1 | A18081100UX0281 | Unique Bargains | A18081100UX0281 | https://octopart.com/a18081100ux0281-unique+bargains-97182774 | 1 |   |   |   |   |   |   |   |   |   |   |   |   | Newegg Business | 9SIV0KK8DW7406 | 5.93 | 5.93 | 5.93 | -2 |   | https://octopart.com/click/track?ak=39ac400e&sig=07dd695&sid=27355&ppid=97182774&vpid=510745618&ct=offers
1 | PTV09A-4020F-B103 | Bourns | PTV09A-4020F-B103 | https://octopart.com/ptv09a-4020f-b103-bourns-1677656 | 1 | PTV09A-4020F-B103-ND | PTV09A-4020F-B103 | Tray | Bulk | 0.83 | 0.74 | 1329 | 815 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0dda3a8&sid=459&ppid=1677656&vpid=54316735&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0e6202d&sid=2401&ppid=1677656&vpid=37823497&ct=offers | Newark | 10C0389 | 0.666 | 0.666 | 0.666 | 311 | 1 | https://octopart.com/click/track?url=http%3A%2F%2Fwww.newark.com%2F10C0389&ak=39ac400e&sig=0bac650&sid=2402&ppid=1677656&ct=offers
6 | KP-2012SYC | Kingbright | KP-2012SYC | https://octopart.com/kp-2012syc-kingbright-7381223 | 6 |   |   |   |   |   |   |   |   |   |   |   |   | TME | KP-2012SYC | 0.1305 | 0.7828 | 0.7828 | 16545 | 5 | https://octopart.com/click/track?ak=39ac400e&sig=0e786ef&sid=1532&ppid=7381223&vpid=88625567&ct=offers



Hey Paul! I smashed together a BOM off of octopart. I had to guess a lot (as parts don't ever match between sites and distributors). This BOM does not include the battery holder. I'll update my test copy accordingly. Does this look anywhere near what you have or will I have an issue somewhere?

Edit: Octopart, octoprint... What's the difference?

**Comment by cmcraft** [comment]
https://octopart.com/120591-1-te+connectivity-46505236?r=sp&s=3kDbhNDNT5emb2So2qJi7g

This may match your button cell holder from AliExpress.

**Comment by PaulKlinger** [comment]
Looks good, just a few things:
- the potentiometer knob is not round, so you might have to glue the 3d printed cap on (or redesign it)
- these resistors are ludicrously expensive, even on digikey you can get some for ~1/50th the price (e.g. [CR0805-JW-103ELFCT-ND](https://www.digikey.at/product-detail/en/bourns-inc/CR0805-JW-103ELF/CR0805-JW-103ELFCT-ND/3592918))

**Comment by PaulKlinger** [comment]
The button cell holders are different, mine have pins that are 20.16mm apart. I'll try to find one than matches on octopart.

**Comment by cmcraft** [comment]
Thanks for the catch on those resistors! I just randomly clicked on an entry and didn't check the price. 


Qty | Line Item | Manufacturer | MPN | Octopart URL | Schematic Reference | Internal Part Number | Description | Total Qty (@ Batch Size: 1) | SKU | SKU | Packaging | Packaging | Unit Price (@ Batch Size: 1) | Unit Price (@ Batch Size: 1) | In Stock | In Stock | MOQ | MOQ | URL | URL | Distributor [Lowest Price (Overall)] | SKU [Lowest Price (Overall)] | Packaging [Lowest Price (Overall)] | Unit Price (@ Batch Size: 1) [Lowest Price   (Overall)] | Line Total [Lowest Price (Overall)] | Batch Total [Lowest Price (Overall)] | In Stock [Lowest Price (Overall)] | MOQ [Lowest Price (Overall)] | URL [Lowest Price (Overall)] | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser |   |   |   |   |   |   |   |   |   |  
1 | ATTINY1614-SSFR | Microchip | ATTINY1614-SSFR | https://octopart.com/attiny1614-ssfr-microchip-82181131 | 1 | ATTINY1614-SSFRCT-ND | ATTINY1614-SSFR | Cut Tape | 0.75 | 0.75 | 4187 | 4507 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0a83d4a&sid=459&ppid=82181131&vpid=431492422&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=014fdb8&sid=2401&ppid=82181131&vpid=447257214&ct=offers | Arrow Electronics, Inc. | ATTINY1614-SSFR | Cut Tape | 0.7314 | 0.7314 | 0.7314 | 2771 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=05768f2&sid=1106&ppid=82181131&vpid=473294420&ct=offers
1 | GRM21BR61C106KE15L | Murata | GRM21BR61C106KE15L | https://octopart.com/grm21br61c106ke15l-murata-197438 | 1 | 490-3886-1-ND | GRM21BR61C106KE15L | Cut Tape | 0.32 | 0.36 | 5E+06 | 1E+06 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0d5de69&sid=459&ppid=197438&vpid=1827596&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0187e19&sid=2401&ppid=197438&vpid=38925211&ct=offers | Conrad | 450891 |   | 0.1585 | 0.1585 | 0.1585 | 3263 |   | https://octopart.com/click/track?ak=39ac400e&sig=0ed9acd&sid=14587&ppid=197438&vpid=410932726&ct=offers
1 | A18081100UX0281 | Unique Bargains | A18081100UX0281 | https://octopart.com/a18081100ux0281-unique+bargains-97182774 | 1 |   |   |   |   |   |   |   |   |   |   |   |   | Newegg Business | 9SIV0KK8DW7406 | 5.93 | 5.93 | 5.93 | -2 |   | https://octopart.com/click/track?ak=39ac400e&sig=07dd695&sid=27355&ppid=97182774&vpid=510745618&ct=offers
1 | PTV09A-4020F-B103 | Bourns | PTV09A-4020F-B103 | https://octopart.com/ptv09a-4020f-b103-bourns-1677656 | 1 | PTV09A-4020F-B103-ND | PTV09A-4020F-B103 | Tray | Bulk | 0.83 | 0.74 | 1329 | 815 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0dda3a8&sid=459&ppid=1677656&vpid=54316735&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0e6202d&sid=2401&ppid=1677656&vpid=37823497&ct=offers | Newark | 10C0389 | 0.666 | 0.666 | 0.666 | 311 | 1 | https://octopart.com/click/track?url=http%3A%2F%2Fwww.newark.com%2F10C0389&ak=39ac400e&sig=0bac650&sid=2402&ppid=1677656&ct=offers
6 | KP-2012SYC | Kingbright | KP-2012SYC | https://octopart.com/kp-2012syc-kingbright-7381223 | 6 |   |   |   |   |   |   |   |   |   |   |   |   | TME | KP-2012SYC | 0.1305 | 0.7828 | 0.7828 | 16545 | 5 | https://octopart.com/click/track?ak=39ac400e&sig=0e786ef&sid=1532&ppid=7381223&vpid=88625567&ct=offers
1 | 120591-1 | TE Connectivity | 120591-1 | https://octopart.com/120591-1-te+connectivity-46505236 | 1 | A99328-ND | 120591-1 | Bulk | Tray | 2.03 | 2.19 | 2468 | 2954 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0cf64a3&sid=459&ppid=46505236&vpid=198672187&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=002535f&sid=2401&ppid=46505236&vpid=119940512&ct=offers | Newark | 33B4715 | 0.852 | 0.852 | 0.852 | 2425 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=042aa95&sid=2402&ppid=46505236&vpid=118727995&ct=offers
6 | CR0805-JW-103ELF | Bourns | CR0805-JW-103ELF | https://octopart.com/cr0805-jw-103elf-bourns-975882 | 6 | CR0805-JW-103ELFCT-ND | CR0805-JW-103ELF | Cut Tape | 0.1 | 0.1 | 352715 | 0 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0185210&sid=459&ppid=975882&vpid=54325049&ct=offers | https://octopart.com/click/track?c=1&ak=39ac400e&sig=01cc0e2&sid=2401&ppid=975882&vpid=37710188&ct=offers | Avnet | 02J2519 | 0.006 | 0.036 | 0.036 | 0 | 1 | https://octopart.com/click/track?c=1&ak=39ac400e&sig=0721438&sid=5822&ppid=975882&vpid=503034749&ct=offers

Here's what I've got so far. The resistors alone lowered the unit price to around 9.2 USD

**Comment by PaulKlinger** [comment]
[This battery holder](https://octopart.com/bs-7-memory+protection+devices-29784142?r=sp&s=GjjVx-vhSE67zNZE4KZhIQ) looks pretty much like mine, except for the color.

[And this one](https://octopart.com/1066-keystone-27174?r=sp&s=-qgaYbkhSDG4a-F_Cvl6Tg) looks a bit different but should also fit.

**Comment by cmcraft** [comment]
Substituted into the intermediate BOM

**Comment by PaulKlinger** [comment]
You can probably shave of a few dollars more, but honestly, for small quantities, the chinese suppliers are just so much cheaper. E.g. if you buy these:
- [Capacitors (x100) - $1.94](https://www.aliexpress.com/item/100pcs-3-3PF-47UF-0805-SMD-100V-X7R-10-100nf-0-1uf-104K-104-22UF-4/32882102243.html)
- [Resistors (x100) - $0.63](https://www.aliexpress.com/item/100Pcs-0805-SMD-1-4W-0R-10M-chip-resistor-0-10R-100R-220R-330R-470R-1K/32858225842.html)
- [Potentiometers (x10) - $1.41](https://www.aliexpress.com/item/10pcs-x-RV09-vertical-12-5mm-Shaft-5K-10K-50K-100K-0932-Adjustable-Resistor-9-type/32897258726.html)
- [Battery holder (x10) - $0.65](https://www.aliexpress.com/item/10PCS-Battery-Button-Cell-Holder-Socket-Case-CR2032-battery-holder-2032/32819924096.html)
- [LEDs (x100) - $0.55](https://www.aliexpress.com/item/Free-Ship-100PCS-0805-light-emitting-diode-SMD-LED-bead-Red-Yellow-Green-White-Blue-Orange/32871959868.html)
- [switch (x100) - $1.43](https://www.aliexpress.com/item/50pcs-3-6mm-SMD-light-touch-switch-2-pin-side-button-Micro-switch-button-switches-3mm/32311331185.html)

(everything including shipping to Austria)

That's < $0.9 / unit for everything except the microcontroller when building 10 units, and < $1.55 / unit total. (And you have a lot of components left over after building 10, like 80 switches, 40 LEDs, 90 capacitors,...)

**Comment by cmcraft** [comment]
That's true. I have an issue with wanting 'just' enough for a project.

**Comment by PaulKlinger** [comment]
Anyway, the octopart BOM will still be really useful for documentation. Items randomly disappear from aliexpress every few months so the links don't last very long.

Can you post the finished version when you're done? Thanks a lot for the help! 😃

**Comment by cmcraft** [comment]
No problem!

Here's the component BOM from Octopart


Qty | Line Item | Manufacturer | MPN | Octopart URL | Schematic Reference | Internal Part Number | Description | Total Qty (@ Batch Size: 1) | SKU | SKU | Packaging | Packaging | Unit Price (@ Batch Size: 1) | Unit Price (@ Batch Size: 1) | In Stock | In Stock | MOQ | MOQ | URL | URL | Distributor [Lowest Price (Overall)] | SKU [Lowest Price (Overall)] | Packaging [Lowest Price (Overall)] | Unit Price (@ Batch Size: 1) [Lowest Price   (Overall)] | Line Total [Lowest Price (Overall)] | Batch Total [Lowest Price (Overall)] | In Stock [Lowest Price (Overall)] | MOQ [Lowest Price (Overall)] | URL [Lowest Price (Overall)] | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser | Digi-Key | Mouser |   |   |   |   |   |   |   |   |   |  
1 | ATTINY1614-SSFR | Microchip | ATTINY1614-SSFR | https://octopart.com/attiny1614-ssfr-microchip-82181131 | 1 | ATTINY1614-SSFRCT-ND | ATTINY1614-SSFR | Cut Tape | 0.75 | 0.75 | 4187 | 4507 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0a83d4a&sid=459&ppid=82181131&vpid=431492422&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=014fdb8&sid=2401&ppid=82181131&vpid=447257214&ct=offers | Arrow Electronics, Inc. | ATTINY1614-SSFR | Cut Tape | 0.7314 | 0.7314 | 0.7314 | 2771 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=05768f2&sid=1106&ppid=82181131&vpid=473294420&ct=offers
1 | GRM21BR61C106KE15L | Murata | GRM21BR61C106KE15L | https://octopart.com/grm21br61c106ke15l-murata-197438 | 1 | 490-3886-1-ND | GRM21BR61C106KE15L | Cut Tape | 0.32 | 0.36 | 5E+06 | 1E+06 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0d5de69&sid=459&ppid=197438&vpid=1827596&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0187e19&sid=2401&ppid=197438&vpid=38925211&ct=offers | Conrad | 450891 |   | 0.1585 | 0.1585 | 0.1585 | 3263 |   | https://octopart.com/click/track?ak=39ac400e&sig=0ed9acd&sid=14587&ppid=197438&vpid=410932726&ct=offers
1 | A18081100UX0281 | Unique Bargains | A18081100UX0281 | https://octopart.com/a18081100ux0281-unique+bargains-97182774 | 1 |   |   |   |   |   |   |   |   |   |   |   |   | Newegg Business | 9SIV0KK8DW7406 | 5.93 | 5.93 | 5.93 | -2 |   | https://octopart.com/click/track?ak=39ac400e&sig=07dd695&sid=27355&ppid=97182774&vpid=510745618&ct=offers
1 | PTV09A-4020F-B103 | Bourns | PTV09A-4020F-B103 | https://octopart.com/ptv09a-4020f-b103-bourns-1677656 | 1 | PTV09A-4020F-B103-ND | PTV09A-4020F-B103 | Tray | Bulk | 0.83 | 0.74 | 1329 | 815 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0dda3a8&sid=459&ppid=1677656&vpid=54316735&ct=offers | https://octopart.com/click/track?ak=39ac400e&sig=0e6202d&sid=2401&ppid=1677656&vpid=37823497&ct=offers | Newark | 10C0389 | 0.666 | 0.666 | 0.666 | 311 | 1 | https://octopart.com/click/track?url=http%3A%2F%2Fwww.newark.com%2F10C0389&ak=39ac400e&sig=0bac650&sid=2402&ppid=1677656&ct=offers
6 | KP-2012SYC | Kingbright | KP-2012SYC | https://octopart.com/kp-2012syc-kingbright-7381223 | 6 |   |   |   |   |   |   |   |   |   |   |   |   | TME | KP-2012SYC | 0.1305 | 0.7828 | 0.7828 | 16545 | 5 | https://octopart.com/click/track?ak=39ac400e&sig=0e786ef&sid=1532&ppid=7381223&vpid=88625567&ct=offers
6 | CR0805-JW-103ELF | Bourns | CR0805-JW-103ELF | https://octopart.com/cr0805-jw-103elf-bourns-975882 | 6 | CR0805-JW-103ELFCT-ND | CR0805-JW-103ELF | Cut Tape | 0.1 | 0.1 | 352715 | 0 | 1 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0185210&sid=459&ppid=975882&vpid=54325049&ct=offers | https://octopart.com/click/track?c=1&ak=39ac400e&sig=01cc0e2&sid=2401&ppid=975882&vpid=37710188&ct=offers | Avnet | 02J2519 | 0.006 | 0.036 | 0.036 | 0 | 1 | https://octopart.com/click/track?c=1&ak=39ac400e&sig=0721438&sid=5822&ppid=975882&vpid=503034749&ct=offers
1 | BS-7 | Memory Protection Devices | BS-7 | https://octopart.com/bs-7-memory+protection+devices-29784142 | 1 | BS-7-ND | Bulk |   | 0.75 |   | 23822 |   | 1 |   | https://octopart.com/click/track?ak=39ac400e&sig=0f913ab&sid=459&ppid=29784142&vpid=1941628&ct=offers | Onlinecomponents.com | BS-7 |   | 0.73 | 0.73 | 0.73 | 1361 | 1 | https://octopart.com/click/track?ak=39ac400e&sig=0dbb6e0&sid=2429&ppid=29784142&vpid=446090856&ct=offers

**Comment by PaulKlinger** [comment]
Great! I've [added it](https://github.com/PaulKlinger/ndice/blob/master/pcb/octopart_bom.md) to the pcb folder and mentioned it in the readme.
Thanks again :)

**Comment by cmcraft** [comment]
No prob! One final question! What did you use to socket the ATTINY1614-SSFR for programming? I have a Teensy 3.2 for the actual programming.

**Comment by PaulKlinger** [comment]
Nothing! I program it on the PCB, using the three pads on the left side. I wrote a bit about that in the readme:

> The oval hole on the left side of the top cover is used to reprogram the MCU without dissasembling the die. I use a small jig with three spring loaded pogo pins ([bought here](https://www.aliexpress.com/item/50pcs-set-New-P75-B1-Dia-1-02mm-100g-Cusp-Spear-Spring-Loaded-Test-Probes-Pogo/32767984398.html)) to connect to the pads underneath (you need to put some solder in the three holes to make a surface for the pins to push against). The holes are the standard pin header ones, 0.1 inch apart, so you can just solder the pogo pins into three adjacent holes of a protoboard. From the buttons down the three pads are VCC, UPDI data, GND. Here's [a picture](https://raw.githubusercontent.com/PaulKlinger/ndice/master/programming_jig.jpg) of the programming jig with a PICkit 4 connected (the PICkit doesn't provide power, so that comes from the usb). (I don't really recommend the pickit, the AVR support is still in beta and there are some irritating bugs.)

If you don't want to use pogo pins you can just temporarily solder some wires to that header.

Make sure that your setup can actually program the Attiny1614, it uses the new UPDI interface instead of the old serial one (so it's different from e.g. the ATtiny85). (I really like that you only need 3 connections now: power, ground, and data.)
